version: '3'

services:
  nginx:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - backend
      - db

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    environment:
      - APP_NAME=Laravel
      - APP_ENV=prod
      - APP_DEBUG=false
      - DB_USER=${DB_USERNAME}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${BACKEND_PORT}:80
    depends_on:
      - db

  db:
    image: mariadb:10.7.3-focal
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
